db:
  username: SYSDBA
  password: SYSDBA001
  port: 5237
  ip: 127.0.0.1
  database: DKYPW
update-url: localhost:18080
slice: 1000
redis:
  username:
  password:
  url: localhost:6379
  db: 0
test:
  on: false
  on-devices:
    - "1111"
    - "222"
  off-devices: []