database:
  source:
    driver: "dameng"
    dsn: ""
    options:
      user: "SYSDBA"
      password: "SYSDBA001"
      host: "127.0.0.1"
      port: "5237"
      schema: "WEB"
      appName: "数据库同步工具"
      connectTimeout: "30000"

  target:
    driver: "dameng"
    dsn: ""
    options:
      user: "SYSDBA"
      password: "SYSDBA"
      host: "127.0.0.1"
      port: "5236"
      schema: "WEB"
      appName: "数据库同步工具"
      connectTimeout: "30000"

sync:
  enable_soft_delete: true
  hard_delete: true
  batch_size: 1000

tables:
  - table_name: "WJ_GYYHZSB"
    primary_key: ["ID"]
    schema1: "WEB"
    schema2: "WEB"
    soft_delete_field: ""
    soft_delete_value: ""
    batch_size: 5000
#    where_condition:
#      owner: "350300"