database:
  source:
    driver: "dameng"
    dsn: ""
    options:
      user: "DKYPW"
      password: "Dkypw@1234"
      host: "127.0.0.1"
      port: "5237"
      schema: "DKYPW"
      appName: "数据库同步工具"
      connectTimeout: "30000"

  target:
    driver: "dameng"
    dsn: ""
    options:
      user: "DKYPW"
      password: "Dkypw@1234"
      host: "127.0.0.1"
      port: "5238"
      schema: "DKYPW_TEST"
      appName: "数据库同步工具"
      connectTimeout: "30000"

sync:
  enable_soft_delete: true
  hard_delete: true
  batch_size: 1000

tables:
  # C表 - 先处理 (直接删除)
  - table_name: "SG_DEV_DDIS_C"
    primary_key: ["DCLOUD_ID"]
    schema1: "DKYPW"
    schema2: "DKYPW"
    soft_delete_field: ""
    soft_delete_value: ""
    batch_size: 1500
    where_condition:
      owner: "350300"